#!/usr/bin/env bash
menu_list="flameshot\nflameshot-gui\nscan\npulsemixer"
sel=$(echo -e "$menu_list" | dmenu $@ -i -l 2)

case "$sel" in
    pulsemixer) termite -e pulsemixer &;;
    scan)  simple-scan & ;;
    flameshot) flameshot &;;
    flameshot-gui) flameshot gui &;;
esac
